github: [wanghaisheng]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
ko_fi: tiktoka33697
liberapay: HeisenBerg
open_collective: tiktoka-official
patreon: USERNAME
